# first party
from delphi.epidata.acquisition.covid_hosp.common.database import Database as BaseDatabase
from delphi.epidata.acquisition.covid_hosp.common.utils import Utils


class Database(BaseDatabase):

  TABLE_NAME = 'covid_hosp_facility'

  # These are the names that appear in the CSV header, in order of appearance
  # in the database table, along with corresponding data type converters.
  # However, note that the corresponding database column names may be shorter
  # due to constraints on the length of column names. See
  # /src/ddl/covid_hosp.sql for more information.
  ORDERED_CSV_COLUMNS = [
    ('hospital_pk', str),
    ('collection_week', Utils.int_from_date),
    ('state', str),
    ('ccn', str),
    ('hospital_name', str),
    ('address', str),
    ('city', str),
    ('zip', str),
    ('hospital_subtype', str),
    ('fips_code', str),
    ('is_metro_micro', Utils.parse_bool),
    ('total_beds_7_day_avg', float),
    ('all_adult_hospital_beds_7_day_avg', float),
    ('all_adult_hospital_inpatient_beds_7_day_avg', float),
    ('inpatient_beds_used_7_day_avg', float),
    ('all_adult_hospital_inpatient_bed_occupied_7_day_avg', float),
    ('total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg', float),
    ('total_adult_patients_hospitalized_confirmed_covid_7_day_avg', float),
    ('total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg', float),
    ('total_pediatric_patients_hospitalized_confirmed_covid_7_day_avg', float),
    ('inpatient_beds_7_day_avg', float),
    ('total_icu_beds_7_day_avg', float),
    ('total_staffed_adult_icu_beds_7_day_avg', float),
    ('icu_beds_used_7_day_avg', float),
    ('staffed_adult_icu_bed_occupancy_7_day_avg', float),
    ('staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_avg', float),
    ('staffed_icu_adult_patients_confirmed_covid_7_day_avg', float),
    ('total_patients_hospitalized_confirmed_influenza_7_day_avg', float),
    ('icu_patients_confirmed_influenza_7_day_avg', float),
    ('total_patients_hospitalized_confirmed_influenza_and_covid_7_day_avg', float),
    ('total_beds_7_day_sum', int),
    ('all_adult_hospital_beds_7_day_sum', int),
    ('all_adult_hospital_inpatient_beds_7_day_sum', int),
    ('inpatient_beds_used_7_day_sum', int),
    ('all_adult_hospital_inpatient_bed_occupied_7_day_sum', int),
    ('total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum', int),
    ('total_adult_patients_hospitalized_confirmed_covid_7_day_sum', int),
    ('total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum', int),
    ('total_pediatric_patients_hospitalized_confirmed_covid_7_day_sum', int),
    ('inpatient_beds_7_day_sum', int),
    ('total_icu_beds_7_day_sum', int),
    ('total_staffed_adult_icu_beds_7_day_sum', int),
    ('icu_beds_used_7_day_sum', int),
    ('staffed_adult_icu_bed_occupancy_7_day_sum', int),
    ('staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_sum', int),
    ('staffed_icu_adult_patients_confirmed_covid_7_day_sum', int),
    ('total_patients_hospitalized_confirmed_influenza_7_day_sum', int),
    ('icu_patients_confirmed_influenza_7_day_sum', int),
    ('total_patients_hospitalized_confirmed_influenza_and_covid_7_day_sum', int),
    ('total_beds_7_day_coverage', int),
    ('all_adult_hospital_beds_7_day_coverage', int),
    ('all_adult_hospital_inpatient_beds_7_day_coverage', int),
    ('inpatient_beds_used_7_day_coverage', int),
    ('all_adult_hospital_inpatient_bed_occupied_7_day_coverage', int),
    ('total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_coverage', int),
    ('total_adult_patients_hospitalized_confirmed_covid_7_day_coverage', int),
    ('total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_coverage', int),
    ('total_pediatric_patients_hospitalized_confirmed_covid_7_day_coverage', int),
    ('inpatient_beds_7_day_coverage', int),
    ('total_icu_beds_7_day_coverage', int),
    ('total_staffed_adult_icu_beds_7_day_coverage', int),
    ('icu_beds_used_7_day_coverage', int),
    ('staffed_adult_icu_bed_occupancy_7_day_coverage', int),
    ('staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_coverage', int),
    ('staffed_icu_adult_patients_confirmed_covid_7_day_coverage', int),
    ('total_patients_hospitalized_confirmed_influenza_7_day_coverage', int),
    ('icu_patients_confirmed_influenza_7_day_coverage', int),
    ('total_patients_hospitalized_confirmed_influenza_and_covid_7_day_coverage', int),
    ('previous_day_admission_adult_covid_confirmed_7_day_sum', int),
    ('previous_day_admission_adult_covid_confirmed_18-19_7_day_sum', int),
    ('previous_day_admission_adult_covid_confirmed_20-29_7_day_sum', int),
    ('previous_day_admission_adult_covid_confirmed_30-39_7_day_sum', int),
    ('previous_day_admission_adult_covid_confirmed_40-49_7_day_sum', int),
    ('previous_day_admission_adult_covid_confirmed_50-59_7_day_sum', int),
    ('previous_day_admission_adult_covid_confirmed_60-69_7_day_sum', int),
    ('previous_day_admission_adult_covid_confirmed_70-79_7_day_sum', int),
    ('previous_day_admission_adult_covid_confirmed_80+_7_day_sum', int),
    ('previous_day_admission_adult_covid_confirmed_unknown_7_day_sum', int),
    ('previous_day_admission_pediatric_covid_confirmed_7_day_sum', int),
    ('previous_day_covid_ED_visits_7_day_sum', int),
    ('previous_day_admission_adult_covid_suspected_7_day_sum', int),
    ('previous_day_admission_adult_covid_suspected_18-19_7_day_sum', int),
    ('previous_day_admission_adult_covid_suspected_20-29_7_day_sum', int),
    ('previous_day_admission_adult_covid_suspected_30-39_7_day_sum', int),
    ('previous_day_admission_adult_covid_suspected_40-49_7_day_sum', int),
    ('previous_day_admission_adult_covid_suspected_50-59_7_day_sum', int),
    ('previous_day_admission_adult_covid_suspected_60-69_7_day_sum', int),
    ('previous_day_admission_adult_covid_suspected_70-79_7_day_sum', int),
    ('previous_day_admission_adult_covid_suspected_80+_7_day_sum', int),
    ('previous_day_admission_adult_covid_suspected_unknown_7_day_sum', int),
    ('previous_day_admission_pediatric_covid_suspected_7_day_sum', int),
    ('previous_day_total_ED_visits_7_day_sum', int),
    ('previous_day_admission_influenza_confirmed_7_day_sum', int),
  ]

  def __init__(self, *args, **kwargs):
    super().__init__(
        *args,
        **kwargs,
        table_name=Database.TABLE_NAME,
        columns_and_types=Database.ORDERED_CSV_COLUMNS)
