[tool.black]
line-length = 100
target-version = ['py38']
include = 'server,tests/server'

[tool.pylint]
    [tool.pylint.'MESSAGES CONTROL']
    max-line-length = 100
    disable = [
        'logging-format-interpolation',
        # Allow pytest functions to be part of a class
        'no-self-use',
        'too-many-locals',
        'too-many-arguments',
        # Allow pytest classes to have one test
        'too-few-public-methods',
    ]

    [tool.pylint.'BASIC']
    # Allow arbitrarily short-named variables.
    variable-rgx = ['[a-z_][a-z0-9_]*']
    argument-rgx = [ '[a-z_][a-z0-9_]*' ]
    attr-rgx = ['[a-z_][a-z0-9_]*']

    [tool.pylint.'DESIGN']
    ignored-argument-names = ['(_.*|run_as_module)']
