
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-25T20:00:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c4d2e89ca029467a0010abdd13d6ec9ead063d9e",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
