USE epidata;
/*
TODO: briefly describe data source and define all columns.
*/

CREATE TABLE `rvdss` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `epiweek` int(6) NOT NULL,
  `time_value` int(8) NOT NULL,
  `time_type` char(4) NOT NULL,
  `issue` int(8) NOT NULL,
  `geo_type` char(8) NOT NULL,
  `geo_value` char(35) NOT NULL,
  `sarscov2_tests` int(10),
  `sarscov2_positive_tests` int(10),
  `sarscov2_pct_positive` int(10),
  `flu_tests` int(10),
  `flua_tests` int(10),
  `flub_tests` int(10),
  `flu_positive_tests` int(10),
  `flu_pct_positive` int(10),
  `fluah1n1pdm09_positive_tests` int(10),
  `fluah3_positive_tests` int(10),
  `fluauns_positive_tests` int(10),
  `flua_positive_tests` int(10),
  `flua_pct_positive` int(10),
  `flub_positive_tests` int(10),
  `flub_pct_positive` int(10),
  `rsv_tests` int(10),
  `rsv_positive_tests` int(10),
  `rsv_pct_positive` int(10),
  `hpiv_tests` int(10),
  `hpiv1_positive_tests` int(10),
  `hpiv2_positive_tests` int(10),
  `hpiv3_positive_tests` int(10),
  `hpiv4_positive_tests` int(10),
  `hpivother_positive_tests` int(10),
  `hpiv_positive_tests` int(10),
  `hpiv_pct_positive` int(10),
  `adv_tests` int(10),
  `adv_positive_tests` int(10),
  `adv_pct_positive` int(10),
  `hmpv_tests` int(10),
  `hmpv_positive_tests` int(10),
  `hmpv_pct_positive` int(10),
  `evrv_tests` int(10),
  `evrv_positive_tests` int(10),
  `evrv_pct_positive` int(10),
  `hcov_tests` int(10),
  `hcov_positive_tests` int(10),
  `hcov_pct_positive` int(10),
  `year` int(4),
  PRIMARY KEY (`id`),
  UNIQUE KEY `date` (`epiweek`, `time_value`,`issue`, `geo_type`,`geo_value`),
  KEY `geo_value` (`geo_value`),
  KEY `epiweek` (`epiweek`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;