from . import (
    afhsb,
    cdc,
    covid_hosp_facility_lookup,
    covid_hosp_facility,
    covid_hosp_state_timeseries,
    covidcast_meta,
    covidcast,
    delphi,
    dengue_nowcast,
    dengue_sensors,
    flusurv,
    fluview,
    meta_afhsb,
    meta_norostat,
    meta,
    nidss_dengue,
    nidss_flu,
    norostat,
    nowcast,
    quidel,
    sensors,
    wiki,
)

endpoints = [
    afhsb,
    cdc,
    covid_hosp_facility_lookup,
    covid_hosp_facility,
    covid_hosp_state_timeseries,
    covidcast_meta,
    covidcast,
    delphi,
    dengue_nowcast,
    dengue_sensors,
    flusurv,
    fluview,
    meta_afhsb,
    meta_norostat,
    meta,
    nidss_dengue,
    nidss_flu,
    norostat,
    nowcast,
    quidel,
    sensors,
    wiki,
]

__all__ = ["endpoints"]
