class Articles:

    # Notice that all languages must be two chars, because that `language` column in table `wiki` is CHAR(2)
    available_languages = ["en", "es", "pt"]

    en_articles_flu = [
        "Influenza_B_virus",
        "Influenza_A_virus",
        "Human_flu",
        "Influenzavirus_C",
        "Oseltamivir",
        "Influenza",
        "Influenzavirus_A",
        "Influenza_A_virus_subtype_H1N1",
        "Zanamivir",
        "Influenza-like_illness",
        "Common_cold",
        "Sore_throat",
        "Flu_season",
        "Chills",
        "Fever",
        "Influenza_A_virus_subtype_H2N2",
        "Swine_influenza",
        "Shivering",
        "Canine_influenza",
        "Influenza_A_virus_subtype_H3N2",
        "Neuraminidase_inhibitor",
        "Influenza_pandemic",
        "Viral_pneumonia",
        "Influenza_prevention",
        "Influenza_A_virus_subtype_H1N2",
        "Rhinorrhea",
        "Orthomyxoviridae",
        "Nasal_congestion",
        "Gastroenteritis",
        "Rimantadine",
        "Paracetamol",
        "Amantadine",
        "Viral_neuraminidase",
        "Headache",
        "Influenza_vaccine",
        "Vomiting",
        "Cough",
        "Influenza_A_virus_subtype_H5N1",
        "Nausea",
        "Avian_influenza",
        "Influenza_A_virus_subtype_H7N9",
        "Influenza_A_virus_subtype_H10N7",
        "Influenza_A_virus_subtype_H9N2",
        "Hemagglutinin_(influenza)",
        "Influenza_A_virus_subtype_H7N7",
        "Fatigue_(medical)",
        "Myalgia",
        "Influenza_A_virus_subtype_H7N3",
        "Malaise",
        "Equine_influenza",
        "Cat_flu",
        "Influenza_A_virus_subtype_H3N8",
        "Antiviral_drugs",
        "Influenza_A_virus_subtype_H7N2",
    ]

    en_articles_noro = [
        "Norovirus",
        "Diarrhea",
        "Dehydration",
        "Gastroenteritis",
        "Vomiting",
        "Abdominal_pain",
        "Nausea",
        "Foodborne_illness",
        "Rotavirus",
        "Fecal–oral_route",
        "Intravenous_therapy",
        "Oral_rehydration_therapy",
        "Shellfish",
        "Caliciviridae",
        "Leaky_scanning",
    ]

    en_articles_dengue = [
        "Dengue_fever",
        "Dengue_virus",
        "Aedes",
        "Aedes_aegypti",
        "Dengue_vaccine",
        "Mosquito",
        "Mosquito-borne_disease",
        "Blood_transfusion",
        "Paracetamol",
        "Fever",
        "Headache",
        "Rhinitis",
        "Flavivirus",
        "Exanthem",
        "Myalgia",
        "Arthralgia",
        "Thrombocytopenia",
        "Hematuria",
        "Nosebleed",
        "Petechia",
        "Nausea",
        "Vomiting",
        "Diarrhea",
    ]

    en_articles = list(set(en_articles_flu + en_articles_noro + en_articles_dengue))

    es_articles = [
        "Dengue",
        "Virus_dengue",
        "Aedes",
        "Aedes_aegypti",
        "Culicidae",
        "Transfusión_de_sangre",
        "Paracetamol",
        "Fiebre",
        "Cefalea",
        "Coriza",
        "Flavivirus",
        "Exantema",
        "Mosquito",
        "Mialgia",
        "Artralgia",
        "Trombocitopenia",
        "Hematuria",
        "Epistaxis",
        "Petequia",
        "Náusea",
        "Vómito",
        "Diarrea",
    ]

    pt_articles = [
        "Dengue",
        "Vírus_da_dengue",
        "Aedes",
        "Aedes_aegypti",
        "Culicidae",
        "Transfusão_de_sangue",
        "Paracetamol",
        "Febre",
        "Cefaleia",
        "Coriza",
        "Flavivírus",
        "Exantema",
        "Mialgia",
        "Artralgia",
        "Trombocitopenia",
        "Hematúria",
        "Epistaxe",
        "Petéquia",
        "Náusea",
        "Vômito",
        "Diarreia",
    ]
