name: Lint

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: "requirements.lint.txt"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lint.txt
      - name: Commit Range
        id: commit-range
        uses: akaihola/darker/.github/actions/commit-range@1.7.1
      - name: Run lint
        run: |
          inv lint --revision=${{ steps.commit-range.outputs.commit-range }}
