# start with the `delphi_python` image, which is built from repos/delphi/operations/dev/docker/python/Dockerfile
FROM delphi_python

RUN pip install --no-cache-dir -r repos/delphi/delphi-epidata/requirements.txt -r repos/delphi/delphi-epidata/requirements.dev.txt
